name: Compile Mod

on:
  workflow_dispatch:

jobs:
  minecraft:
    name: Building Mod
    runs-on: windows-lastest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-jdk@4.2.1
      with:
        distribution: "temurin"
        java-version: "8"
    - uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
    - run: |
       gradle build
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: Source
        path: .
